common: &common
  from_email: steve@coachstevo.com
  base_url: http://example.com
  questionnaires:
    io: http://example.com/io/
    si: http://example.com/si/
    sdtc: http://example.com/sdtc/

development:
  <<: *common
  sendmail: false
  
production:
  <<: *common
  sendmail: true